In [1]:
from bs4 import BeautifulSoup
from selenium import webdriver
import numpy as np
import requests
import pandas as pd

In [2]:
#인구 데이터
data = [{"gu":"\uc885\ub85c\uad6c","dong":"\uc0ac\uc9c1\ub3d9","household":"4,717","pop_total_male":"4,442","pop_total_female":"5,345","over_65":"1,836"},{"gu":"\uc885\ub85c\uad6c","dong":"\uc0bc\uccad\ub3d9","household":"1,370","pop_total_male":"1,427","pop_total_female":"1,546","over_65":"683"},{"gu":"\uc885\ub85c\uad6c","dong":"\ubd80\uc554\ub3d9","household":"4,346","pop_total_male":"4,953","pop_total_female":"5,468","over_65":"1,802"},{"gu":"\uc885\ub85c\uad6c","dong":"\ud3c9\ucc3d\ub3d9","household":"7,517","pop_total_male":"8,752","pop_total_female":"9,944","over_65":"3,362"},{"gu":"\uc885\ub85c\uad6c","dong":"\ubb34\uc545\ub3d9","household":"3,203","pop_total_male":"4,043","pop_total_female":"4,648","over_65":"1,446"},{"gu":"\uc885\ub85c\uad6c","dong":"\uad50\ub0a8\ub3d9","household":"4,595","pop_total_male":"4,962","pop_total_female":"5,724","over_65":"1,600"},{"gu":"\uc885\ub85c\uad6c","dong":"\uac00\ud68c\ub3d9","household":"2,074","pop_total_male":"2,069","pop_total_female":"2,384","over_65":"932"},{"gu":"\uc885\ub85c\uad6c","dong":"\uc885\ub85c1.2.3.4\uac00\ub3d9","household":"5,232","pop_total_male":"5,010","pop_total_female":"3,516","over_65":"1,985"},{"gu":"\uc885\ub85c\uad6c","dong":"\uc885\ub85c5\u00b76\uac00\ub3d9","household":"3,406","pop_total_male":"3,148","pop_total_female":"2,652","over_65":"1,135"},{"gu":"\uc885\ub85c\uad6c","dong":"\uc774\ud654\ub3d9","household":"4,463","pop_total_male":"3,841","pop_total_female":"4,495","over_65":"1,400"},{"gu":"\uc885\ub85c\uad6c","dong":"\ucc3d\uc2e01\ub3d9","household":"2,952","pop_total_male":"3,237","pop_total_female":"2,779","over_65":"1,245"},{"gu":"\uc885\ub85c\uad6c","dong":"\ucc3d\uc2e02\ub3d9","household":"4,137","pop_total_male":"4,930","pop_total_female":"4,724","over_65":"1,751"},{"gu":"\uc885\ub85c\uad6c","dong":"\ucc3d\uc2e03\ub3d9","household":"2,905","pop_total_male":"3,526","pop_total_female":"3,663","over_65":"1,240"},{"gu":"\uc885\ub85c\uad6c","dong":"\uc22d\uc7781\ub3d9","household":"2,990","pop_total_male":"3,138","pop_total_female":"3,356","over_65":"1,192"},{"gu":"\uc885\ub85c\uad6c","dong":"\uc22d\uc7782\ub3d9","household":"5,871","pop_total_male":"5,024","pop_total_female":"4,963","over_65":"1,697"},{"gu":"\uc885\ub85c\uad6c","dong":"\uccad\uc6b4\ud6a8\uc790\ub3d9","household":"5,395","pop_total_male":"6,022","pop_total_female":"6,833","over_65":"2,220"},{"gu":"\uc885\ub85c\uad6c","dong":"\ud61c\ud654\ub3d9","household":"9,324","pop_total_male":"9,221","pop_total_female":"10,735","over_65":"2,677"},{"gu":"\uc911\uad6c","dong":"\uc18c\uacf5\ub3d9","household":"1,131","pop_total_male":"1,551","pop_total_female":"1,494","over_65":"295"},{"gu":"\uc911\uad6c","dong":"\ud68c\ud604\ub3d9","household":"3,083","pop_total_male":"3,113","pop_total_female":"2,701","over_65":"1,522"},{"gu":"\uc911\uad6c","dong":"\uba85\ub3d9","household":"1,589","pop_total_male":"1,647","pop_total_female":"2,046","over_65":"791"},{"gu":"\uc911\uad6c","dong":"\ud544\ub3d9","household":"2,338","pop_total_male":"2,432","pop_total_female":"2,405","over_65":"847"},{"gu":"\uc911\uad6c","dong":"\uc7a5\ucda9\ub3d9","household":"2,761","pop_total_male":"2,738","pop_total_female":"2,790","over_65":"822"},{"gu":"\uc911\uad6c","dong":"\uad11\ud76c\ub3d9","household":"3,075","pop_total_male":"3,401","pop_total_female":"3,062","over_65":"1,217"},{"gu":"\uc911\uad6c","dong":"\uc744\uc9c0\ub85c\ub3d9","household":"1,358","pop_total_male":"1,193","pop_total_female":"800","over_65":"510"},{"gu":"\uc911\uad6c","dong":"\uc2e0\ub2f95\ub3d9","household":"5,363","pop_total_male":"5,341","pop_total_female":"5,661","over_65":"1,782"},{"gu":"\uc911\uad6c","dong":"\ud669\ud559\ub3d9","household":"6,935","pop_total_male":"6,567","pop_total_female":"7,154","over_65":"1,970"},{"gu":"\uc911\uad6c","dong":"\uc911\ub9bc\ub3d9","household":"5,860","pop_total_male":"6,464","pop_total_female":"6,432","over_65":"2,074"},{"gu":"\uc911\uad6c","dong":"\uc2e0\ub2f9\ub3d9","household":"4,515","pop_total_male":"4,500","pop_total_female":"4,706","over_65":"1,402"},{"gu":"\uc911\uad6c","dong":"\ub2e4\uc0b0\ub3d9","household":"6,991","pop_total_male":"7,230","pop_total_female":"7,726","over_65":"2,641"},{"gu":"\uc911\uad6c","dong":"\uc57d\uc218\ub3d9","household":"7,828","pop_total_male":"8,287","pop_total_female":"9,292","over_65":"3,707"},{"gu":"\uc911\uad6c","dong":"\uccad\uad6c\ub3d9","household":"6,359","pop_total_male":"6,819","pop_total_female":"7,535","over_65":"2,643"},{"gu":"\uc911\uad6c","dong":"\ub3d9\ud654\ub3d9","household":"4,168","pop_total_male":"5,262","pop_total_female":"5,681","over_65":"1,812"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\ud6c4\uc554\ub3d9","household":"8,594","pop_total_male":"8,955","pop_total_female":"9,399","over_65":"3,073"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\uc6a9\uc0b02\uac00\ub3d9","household":"5,427","pop_total_male":"5,662","pop_total_female":"5,964","over_65":"2,110"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\ub0a8\uc601\ub3d9","household":"5,450","pop_total_male":"5,024","pop_total_female":"3,244","over_65":"1,632"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\uc6d0\ud6a8\ub85c2\ub3d9","household":"6,018","pop_total_male":"6,820","pop_total_female":"7,671","over_65":"2,396"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\ud6a8\ucc3d\ub3d9","household":"4,329","pop_total_male":"4,945","pop_total_female":"5,442","over_65":"1,453"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\uc6a9\ubb38\ub3d9","household":"5,412","pop_total_male":"5,972","pop_total_female":"6,538","over_65":"2,078"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\uc774\ucd0c1\ub3d9","household":"10,356","pop_total_male":"13,761","pop_total_female":"15,568","over_65":"4,527"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\uc774\ucd0c2\ub3d9","household":"3,848","pop_total_male":"4,189","pop_total_female":"4,698","over_65":"1,778"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\uc774\ud0dc\uc6d01\ub3d9","household":"3,839","pop_total_male":"4,789","pop_total_female":"4,364","over_65":"1,614"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\uc774\ud0dc\uc6d02\ub3d9","household":"4,955","pop_total_male":"5,109","pop_total_female":"5,717","over_65":"1,912"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\uc11c\ube59\uace0\ub3d9","household":"5,316","pop_total_male":"6,820","pop_total_female":"7,323","over_65":"2,104"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\ubcf4\uad11\ub3d9","household":"7,724","pop_total_male":"8,252","pop_total_female":"7,771","over_65":"2,788"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\uccad\ud30c\ub3d9","household":"11,028","pop_total_male":"9,576","pop_total_female":"11,088","over_65":"3,364"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\uc6d0\ud6a8\ub85c1\ub3d9","household":"7,956","pop_total_male":"8,127","pop_total_female":"8,665","over_65":"1,994"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\ud55c\uac15\ub85c\ub3d9","household":"10,005","pop_total_male":"9,708","pop_total_female":"10,232","over_65":"3,085"},{"gu":"\uc6a9\uc0b0\uad6c","dong":"\ud55c\ub0a8\ub3d9","household":"11,329","pop_total_male":"11,785","pop_total_female":"12,184","over_65":"3,742"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uc655\uc2ed\ub9ac2\ub3d9","household":"7,626","pop_total_male":"8,589","pop_total_female":"9,079","over_65":"2,573"},{"gu":"\uc131\ub3d9\uad6c","dong":"\ub9c8\uc7a5\ub3d9","household":"10,912","pop_total_male":"11,624","pop_total_female":"12,131","over_65":"3,781"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uc0ac\uadfc\ub3d9","household":"7,696","pop_total_male":"6,702","pop_total_female":"6,809","over_65":"1,501"},{"gu":"\uc131\ub3d9\uad6c","dong":"\ud589\ub2f91\ub3d9","household":"6,617","pop_total_male":"7,126","pop_total_female":"7,701","over_65":"2,115"},{"gu":"\uc131\ub3d9\uad6c","dong":"\ud589\ub2f92\ub3d9","household":"9,482","pop_total_male":"11,463","pop_total_female":"12,978","over_65":"3,715"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uc751\ubd09\ub3d9","household":"6,145","pop_total_male":"7,530","pop_total_female":"8,422","over_65":"2,510"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uae08\ud6381\uac00\ub3d9","household":"6,687","pop_total_male":"7,605","pop_total_female":"8,322","over_65":"2,487"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uae08\ud6384\uac00\ub3d9","household":"6,463","pop_total_male":"7,193","pop_total_female":"7,823","over_65":"2,291"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uc131\uc2181\uac001\ub3d9","household":"7,602","pop_total_male":"8,540","pop_total_female":"8,498","over_65":"2,147"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uc131\uc2181\uac002\ub3d9","household":"6,632","pop_total_male":"6,973","pop_total_female":"7,190","over_65":"1,934"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uc131\uc2182\uac001\ub3d9","household":"8,512","pop_total_male":"9,127","pop_total_female":"8,440","over_65":"2,831"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uc131\uc2182\uac003\ub3d9","household":"5,751","pop_total_male":"5,923","pop_total_female":"5,692","over_65":"1,834"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uc1a1\uc815\ub3d9","household":"5,578","pop_total_male":"5,978","pop_total_female":"5,387","over_65":"1,730"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uc6a9\ub2f5\ub3d9","household":"6,901","pop_total_male":"6,868","pop_total_female":"6,268","over_65":"2,161"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uc655\uc2ed\ub9ac\ub3c4\uc120\ub3d9","household":"11,909","pop_total_male":"13,254","pop_total_female":"14,558","over_65":"3,619"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uae08\ud6382.3\uac00\ub3d9","household":"10,362","pop_total_male":"11,384","pop_total_female":"12,545","over_65":"3,851"},{"gu":"\uc131\ub3d9\uad6c","dong":"\uc625\uc218\ub3d9","household":"11,062","pop_total_male":"12,675","pop_total_female":"14,454","over_65":"3,925"},{"gu":"\uad11\uc9c4\uad6c","dong":"\ud654\uc591\ub3d9","household":"16,608","pop_total_male":"11,587","pop_total_female":"13,676","over_65":"2,278"},{"gu":"\uad11\uc9c4\uad6c","dong":"\uad70\uc790\ub3d9","household":"10,981","pop_total_male":"10,834","pop_total_female":"11,173","over_65":"2,901"},{"gu":"\uad11\uc9c4\uad6c","dong":"\uc911\uace11\ub3d9","household":"8,153","pop_total_male":"7,908","pop_total_female":"8,293","over_65":"2,437"},{"gu":"\uad11\uc9c4\uad6c","dong":"\uc911\uace12\ub3d9","household":"10,604","pop_total_male":"10,685","pop_total_female":"11,815","over_65":"3,150"},{"gu":"\uad11\uc9c4\uad6c","dong":"\uc911\uace13\ub3d9","household":"8,538","pop_total_male":"8,482","pop_total_female":"8,644","over_65":"2,767"},{"gu":"\uad11\uc9c4\uad6c","dong":"\uc911\uace14\ub3d9","household":"13,257","pop_total_male":"14,829","pop_total_female":"15,491","over_65":"4,891"},{"gu":"\uad11\uc9c4\uad6c","dong":"\ub2a5\ub3d9","household":"6,473","pop_total_male":"5,551","pop_total_female":"6,495","over_65":"1,600"},{"gu":"\uad11\uc9c4\uad6c","dong":"\uad6c\uc7581\ub3d9","household":"12,089","pop_total_male":"10,964","pop_total_female":"12,042","over_65":"3,051"},{"gu":"\uad11\uc9c4\uad6c","dong":"\uad6c\uc7582\ub3d9","household":"11,645","pop_total_male":"13,249","pop_total_female":"14,371","over_65":"4,137"},{"gu":"\uad11\uc9c4\uad6c","dong":"\uad6c\uc7583\ub3d9","household":"12,218","pop_total_male":"14,155","pop_total_female":"15,658","over_65":"3,857"},{"gu":"\uad11\uc9c4\uad6c","dong":"\uad11\uc7a5\ub3d9","household":"12,073","pop_total_male":"17,357","pop_total_female":"18,577","over_65":"3,623"},{"gu":"\uad11\uc9c4\uad6c","dong":"\uc790\uc5911\ub3d9","household":"11,646","pop_total_male":"11,465","pop_total_female":"12,410","over_65":"3,302"},{"gu":"\uad11\uc9c4\uad6c","dong":"\uc790\uc5912\ub3d9","household":"11,285","pop_total_male":"12,955","pop_total_female":"13,652","over_65":"3,827"},{"gu":"\uad11\uc9c4\uad6c","dong":"\uc790\uc5913\ub3d9","household":"11,111","pop_total_male":"14,039","pop_total_female":"15,171","over_65":"3,955"},{"gu":"\uad11\uc9c4\uad6c","dong":"\uc790\uc5914\ub3d9","household":"9,626","pop_total_male":"11,023","pop_total_female":"11,374","over_65":"3,681"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\ud68c\uae30\ub3d9","household":"6,209","pop_total_male":"5,784","pop_total_female":"6,895","over_65":"1,543"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\ud718\uacbd1\ub3d9","household":"7,123","pop_total_male":"7,377","pop_total_female":"8,044","over_65":"2,174"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\ud718\uacbd2\ub3d9","household":"11,762","pop_total_male":"12,395","pop_total_female":"12,737","over_65":"3,859"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\uccad\ub7c9\ub9ac\ub3d9","household":"10,495","pop_total_male":"10,764","pop_total_female":"10,824","over_65":"5,331"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\uc6a9\uc2e0\ub3d9","household":"17,906","pop_total_male":"16,421","pop_total_female":"15,958","over_65":"5,611"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\uc81c\uae30\ub3d9","household":"13,181","pop_total_male":"13,620","pop_total_female":"13,517","over_65":"5,597"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\uc804\ub18d1\ub3d9","household":"15,170","pop_total_male":"15,517","pop_total_female":"15,499","over_65":"5,544"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\uc804\ub18d2\ub3d9","household":"7,751","pop_total_male":"9,489","pop_total_female":"10,264","over_65":"3,578"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\ub2f5\uc2ed\ub9ac2\ub3d9","household":"12,981","pop_total_male":"14,691","pop_total_female":"15,417","over_65":"5,382"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\uc7a5\uc5481\ub3d9","household":"17,976","pop_total_male":"19,540","pop_total_female":"19,779","over_65":"6,189"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\uc7a5\uc5482\ub3d9","household":"13,925","pop_total_male":"16,772","pop_total_female":"16,780","over_65":"4,927"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\uc774\ubb381\ub3d9","household":"10,512","pop_total_male":"10,227","pop_total_female":"11,200","over_65":"3,250"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\uc774\ubb382\ub3d9","household":"8,642","pop_total_male":"10,295","pop_total_female":"10,931","over_65":"3,791"},{"gu":"\ub3d9\ub300\ubb38\uad6c","dong":"\ub2f5\uc2ed\ub9ac1\ub3d9","household":"12,818","pop_total_male":"14,345","pop_total_female":"15,298","over_65":"4,041"},{"gu":"\uc911\ub791\uad6c","dong":"\uba74\ubaa92\ub3d9","household":"12,333","pop_total_male":"12,782","pop_total_female":"12,882","over_65":"4,391"},{"gu":"\uc911\ub791\uad6c","dong":"\uba74\ubaa94\ub3d9","household":"9,121","pop_total_male":"9,778","pop_total_female":"9,819","over_65":"3,614"},{"gu":"\uc911\ub791\uad6c","dong":"\uba74\ubaa95\ub3d9","household":"4,521","pop_total_male":"4,897","pop_total_female":"4,778","over_65":"1,655"},{"gu":"\uc911\ub791\uad6c","dong":"\uba74\ubaa97\ub3d9","household":"10,573","pop_total_male":"11,412","pop_total_female":"11,413","over_65":"4,112"},{"gu":"\uc911\ub791\uad6c","dong":"\uc0c1\ubd091\ub3d9","household":"10,345","pop_total_male":"12,371","pop_total_female":"12,928","over_65":"3,575"},{"gu":"\uc911\ub791\uad6c","dong":"\uc0c1\ubd092\ub3d9","household":"11,395","pop_total_male":"9,746","pop_total_female":"10,290","over_65":"2,893"},{"gu":"\uc911\ub791\uad6c","dong":"\uc911\ud6541\ub3d9","household":"9,083","pop_total_male":"10,127","pop_total_female":"10,572","over_65":"3,411"},{"gu":"\uc911\ub791\uad6c","dong":"\uc911\ud6542\ub3d9","household":"13,989","pop_total_male":"13,681","pop_total_female":"12,985","over_65":"4,892"},{"gu":"\uc911\ub791\uad6c","dong":"\ubb351\ub3d9","household":"14,860","pop_total_male":"17,411","pop_total_female":"18,474","over_65":"5,620"},{"gu":"\uc911\ub791\uad6c","dong":"\ubb352\ub3d9","household":"9,262","pop_total_male":"9,696","pop_total_female":"10,093","over_65":"3,381"},{"gu":"\uc911\ub791\uad6c","dong":"\ub9dd\uc6b03\ub3d9","household":"8,457","pop_total_male":"8,916","pop_total_female":"8,854","over_65":"3,191"},{"gu":"\uc911\ub791\uad6c","dong":"\uc2e0\ub0b41\ub3d9","household":"14,887","pop_total_male":"19,803","pop_total_female":"20,808","over_65":"6,509"},{"gu":"\uc911\ub791\uad6c","dong":"\uc2e0\ub0b42\ub3d9","household":"9,071","pop_total_male":"10,296","pop_total_female":"11,320","over_65":"3,825"},{"gu":"\uc911\ub791\uad6c","dong":"\uba74\ubaa9\ubcf8\ub3d9","household":"17,744","pop_total_male":"17,798","pop_total_female":"18,129","over_65":"5,930"},{"gu":"\uc911\ub791\uad6c","dong":"\uba74\ubaa93.8\ub3d9","household":"12,787","pop_total_male":"13,159","pop_total_female":"13,335","over_65":"4,842"},{"gu":"\uc911\ub791\uad6c","dong":"\ub9dd\uc6b0\ubcf8\ub3d9","household":"14,882","pop_total_male":"15,511","pop_total_female":"15,351","over_65":"5,796"},{"gu":"\uc131\ubd81\uad6c","dong":"\ub3c8\uc5541\ub3d9","household":"6,247","pop_total_male":"7,323","pop_total_female":"8,334","over_65":"2,816"},{"gu":"\uc131\ubd81\uad6c","dong":"\ub3c8\uc5542\ub3d9","household":"8,682","pop_total_male":"11,872","pop_total_female":"12,965","over_65":"3,353"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc548\uc554\ub3d9","household":"9,409","pop_total_male":"8,438","pop_total_female":"8,663","over_65":"2,182"},{"gu":"\uc131\ubd81\uad6c","dong":"\ubcf4\ubb38\ub3d9","household":"7,946","pop_total_male":"7,980","pop_total_female":"8,540","over_65":"2,405"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc815\ub9891\ub3d9","household":"7,520","pop_total_male":"9,254","pop_total_female":"10,007","over_65":"3,042"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc815\ub9892\ub3d9","household":"9,719","pop_total_male":"11,493","pop_total_female":"12,256","over_65":"4,307"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc815\ub9893\ub3d9","household":"7,946","pop_total_male":"8,400","pop_total_female":"8,635","over_65":"3,257"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc815\ub9894\ub3d9","household":"10,982","pop_total_male":"12,696","pop_total_female":"13,605","over_65":"4,696"},{"gu":"\uc131\ubd81\uad6c","dong":"\uae38\uc74c1\ub3d9","household":"12,814","pop_total_male":"17,516","pop_total_female":"19,265","over_65":"4,375"},{"gu":"\uc131\ubd81\uad6c","dong":"\uae38\uc74c2\ub3d9","household":"7,109","pop_total_male":"8,353","pop_total_female":"8,940","over_65":"2,538"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc6d4\uace11\ub3d9","household":"10,858","pop_total_male":"13,175","pop_total_female":"14,129","over_65":"4,579"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc6d4\uace12\ub3d9","household":"9,542","pop_total_male":"9,922","pop_total_female":"10,757","over_65":"3,530"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc7a5\uc7041\ub3d9","household":"9,091","pop_total_male":"10,015","pop_total_female":"10,541","over_65":"3,672"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc7a5\uc7042\ub3d9","household":"6,575","pop_total_male":"7,034","pop_total_female":"7,232","over_65":"3,081"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc7a5\uc7043\ub3d9","household":"7,413","pop_total_male":"9,007","pop_total_female":"9,138","over_65":"2,485"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc131\ubd81\ub3d9","household":"8,192","pop_total_male":"8,198","pop_total_female":"9,330","over_65":"3,092"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc0bc\uc120\ub3d9","household":"11,808","pop_total_male":"11,650","pop_total_female":"12,914","over_65":"3,904"},{"gu":"\uc131\ubd81\uad6c","dong":"\ub3d9\uc120\ub3d9","household":"9,354","pop_total_male":"6,799","pop_total_female":"9,585","over_65":"2,260"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc885\uc554\ub3d9","household":"17,296","pop_total_male":"20,260","pop_total_female":"21,334","over_65":"6,484"},{"gu":"\uc131\ubd81\uad6c","dong":"\uc11d\uad00\ub3d9","household":"16,561","pop_total_male":"18,166","pop_total_female":"18,569","over_65":"6,764"},{"gu":"\uac15\ubd81\uad6c","dong":"\ubc881\ub3d9","household":"10,430","pop_total_male":"9,791","pop_total_female":"9,893","over_65":"3,531"},{"gu":"\uac15\ubd81\uad6c","dong":"\ubc882\ub3d9","household":"7,652","pop_total_male":"8,184","pop_total_female":"8,688","over_65":"3,896"},{"gu":"\uac15\ubd81\uad6c","dong":"\ubc883\ub3d9","household":"7,613","pop_total_male":"8,435","pop_total_female":"9,492","over_65":"4,558"},{"gu":"\uac15\ubd81\uad6c","dong":"\uc218\uc7201\ub3d9","household":"10,402","pop_total_male":"10,655","pop_total_female":"10,967","over_65":"4,332"},{"gu":"\uac15\ubd81\uad6c","dong":"\uc218\uc7202\ub3d9","household":"9,672","pop_total_male":"10,427","pop_total_female":"11,369","over_65":"4,610"},{"gu":"\uac15\ubd81\uad6c","dong":"\uc218\uc7203\ub3d9","household":"12,944","pop_total_male":"11,916","pop_total_female":"12,137","over_65":"4,483"},{"gu":"\uac15\ubd81\uad6c","dong":"\uc0bc\uc591\ub3d9","household":"11,436","pop_total_male":"12,523","pop_total_female":"12,653","over_65":"4,833"},{"gu":"\uac15\ubd81\uad6c","dong":"\ubbf8\uc544\ub3d9","household":"11,593","pop_total_male":"10,943","pop_total_female":"11,843","over_65":"4,364"},{"gu":"\uac15\ubd81\uad6c","dong":"\uc1a1\uc911\ub3d9","household":"14,046","pop_total_male":"14,980","pop_total_female":"16,292","over_65":"5,902"},{"gu":"\uac15\ubd81\uad6c","dong":"\uc1a1\ucc9c\ub3d9","household":"13,785","pop_total_male":"14,060","pop_total_female":"14,239","over_65":"5,998"},{"gu":"\uac15\ubd81\uad6c","dong":"\uc0bc\uac01\uc0b0\ub3d9","household":"11,781","pop_total_male":"15,631","pop_total_female":"16,915","over_65":"4,276"},{"gu":"\uac15\ubd81\uad6c","dong":"\uc6b0\uc774\ub3d9","household":"9,553","pop_total_male":"10,326","pop_total_female":"10,884","over_65":"4,665"},{"gu":"\uac15\ubd81\uad6c","dong":"\uc778\uc218\ub3d9","household":"14,652","pop_total_male":"15,518","pop_total_female":"16,634","over_65":"6,890"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\uc30d\ubb381\ub3d9","household":"9,429","pop_total_male":"10,679","pop_total_female":"11,546","over_65":"4,343"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\uc30d\ubb382\ub3d9","household":"8,657","pop_total_male":"9,560","pop_total_female":"10,213","over_65":"3,762"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\uc30d\ubb383\ub3d9","household":"7,908","pop_total_male":"8,301","pop_total_female":"8,817","over_65":"3,324"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\uc30d\ubb384\ub3d9","household":"7,184","pop_total_male":"9,296","pop_total_female":"10,279","over_65":"2,877"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\ubc29\ud5591\ub3d9","household":"12,778","pop_total_male":"14,695","pop_total_female":"14,980","over_65":"5,495"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\ubc29\ud5592\ub3d9","household":"9,573","pop_total_male":"10,497","pop_total_female":"10,338","over_65":"4,180"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\ubc29\ud5593\ub3d9","household":"10,072","pop_total_male":"13,769","pop_total_female":"14,559","over_65":"4,684"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\ucc3d1\ub3d9","household":"10,935","pop_total_male":"12,317","pop_total_female":"13,530","over_65":"4,374"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\ucc3d2\ub3d9","household":"12,424","pop_total_male":"14,809","pop_total_female":"15,456","over_65":"4,965"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\ucc3d3\ub3d9","household":"6,676","pop_total_male":"7,287","pop_total_female":"7,307","over_65":"2,866"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\ucc3d4\ub3d9","household":"10,679","pop_total_male":"13,285","pop_total_female":"14,347","over_65":"4,014"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\ucc3d5\ub3d9","household":"10,139","pop_total_male":"12,227","pop_total_female":"13,294","over_65":"4,136"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\ub3c4\ubd091\ub3d9","household":"10,349","pop_total_male":"11,100","pop_total_female":"10,869","over_65":"5,540"},{"gu":"\ub3c4\ubd09\uad6c","dong":"\ub3c4\ubd092\ub3d9","household":"12,163","pop_total_male":"13,902","pop_total_female":"14,485","over_65":"6,224"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc6d4\uacc41\ub3d9","household":"10,579","pop_total_male":"12,156","pop_total_female":"11,433","over_65":"4,206"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc6d4\uacc42\ub3d9","household":"12,083","pop_total_male":"13,481","pop_total_female":"14,545","over_65":"5,560"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc6d4\uacc43\ub3d9","household":"13,016","pop_total_male":"14,944","pop_total_female":"16,285","over_65":"5,753"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uacf5\ub9892\ub3d9","household":"16,409","pop_total_male":"19,808","pop_total_female":"20,844","over_65":"5,058"},{"gu":"\ub178\uc6d0\uad6c","dong":"\ud558\uacc41\ub3d9","household":"11,768","pop_total_male":"13,720","pop_total_female":"14,739","over_65":"4,237"},{"gu":"\ub178\uc6d0\uad6c","dong":"\ud558\uacc42\ub3d9","household":"8,282","pop_total_male":"10,990","pop_total_female":"12,071","over_65":"3,052"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc911\uacc4\ubcf8\ub3d9","household":"8,789","pop_total_male":"12,448","pop_total_female":"13,004","over_65":"2,573"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc911\uacc41\ub3d9","household":"9,085","pop_total_male":"13,586","pop_total_female":"14,178","over_65":"2,273"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc911\uacc44\ub3d9","household":"8,456","pop_total_male":"10,157","pop_total_female":"10,849","over_65":"3,898"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc0c1\uacc41\ub3d9","household":"15,627","pop_total_male":"19,307","pop_total_female":"20,455","over_65":"6,686"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc0c1\uacc42\ub3d9","household":"8,753","pop_total_male":"10,386","pop_total_female":"10,611","over_65":"3,211"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc0c1\uacc45\ub3d9","household":"10,925","pop_total_male":"12,188","pop_total_female":"12,840","over_65":"4,922"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc0c1\uacc48\ub3d9","household":"9,291","pop_total_male":"11,305","pop_total_female":"12,201","over_65":"2,748"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc0c1\uacc49\ub3d9","household":"8,462","pop_total_male":"10,277","pop_total_female":"11,341","over_65":"3,259"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc0c1\uacc410\ub3d9","household":"6,607","pop_total_male":"7,538","pop_total_female":"8,864","over_65":"2,245"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc0c1\uacc43.4\ub3d9","household":"12,219","pop_total_male":"13,616","pop_total_female":"13,839","over_65":"5,907"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc0c1\uacc46.7\ub3d9","household":"13,926","pop_total_male":"15,855","pop_total_female":"18,296","over_65":"4,756"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uc911\uacc42.3\ub3d9","household":"15,411","pop_total_male":"16,722","pop_total_female":"19,431","over_65":"7,116"},{"gu":"\ub178\uc6d0\uad6c","dong":"\uacf5\ub9891\ub3d9","household":"18,209","pop_total_male":"18,989","pop_total_female":"19,742","over_65":"6,176"},{"gu":"\uc740\ud3c9\uad6c","dong":"\ub179\ubc88\ub3d9","household":"17,255","pop_total_male":"18,230","pop_total_female":"19,915","over_65":"6,781"},{"gu":"\uc740\ud3c9\uad6c","dong":"\ubd88\uad111\ub3d9","household":"17,948","pop_total_male":"19,141","pop_total_female":"21,281","over_65":"7,595"},{"gu":"\uc740\ud3c9\uad6c","dong":"\uac08\ud6041\ub3d9","household":"11,239","pop_total_male":"11,668","pop_total_female":"12,284","over_65":"4,376"},{"gu":"\uc740\ud3c9\uad6c","dong":"\uac08\ud6042\ub3d9","household":"12,617","pop_total_male":"14,114","pop_total_female":"15,596","over_65":"4,803"},{"gu":"\uc740\ud3c9\uad6c","dong":"\uad6c\uc0b0\ub3d9","household":"13,329","pop_total_male":"16,623","pop_total_female":"16,806","over_65":"6,019"},{"gu":"\uc740\ud3c9\uad6c","dong":"\ub300\uc870\ub3d9","household":"14,112","pop_total_male":"12,959","pop_total_female":"14,781","over_65":"4,944"},{"gu":"\uc740\ud3c9\uad6c","dong":"\uc751\uc5541\ub3d9","household":"12,767","pop_total_male":"13,564","pop_total_female":"14,946","over_65":"4,433"},{"gu":"\uc740\ud3c9\uad6c","dong":"\uc751\uc5542\ub3d9","household":"10,843","pop_total_male":"13,426","pop_total_female":"14,195","over_65":"3,656"},{"gu":"\uc740\ud3c9\uad6c","dong":"\uc2e0\uc0ac1\ub3d9","household":"11,794","pop_total_male":"13,591","pop_total_female":"14,549","over_65":"4,755"},{"gu":"\uc740\ud3c9\uad6c","dong":"\uc2e0\uc0ac2\ub3d9","household":"9,101","pop_total_male":"10,649","pop_total_female":"10,739","over_65":"3,783"},{"gu":"\uc740\ud3c9\uad6c","dong":"\uc99d\uc0b0\ub3d9","household":"6,893","pop_total_male":"7,739","pop_total_female":"8,081","over_65":"3,066"},{"gu":"\uc740\ud3c9\uad6c","dong":"\uc218\uc0c9\ub3d9","household":"3,770","pop_total_male":"4,346","pop_total_female":"4,376","over_65":"1,758"},{"gu":"\uc740\ud3c9\uad6c","dong":"\uc9c4\uad00\ub3d9","household":"21,616","pop_total_male":"27,074","pop_total_female":"30,676","over_65":"7,830"},{"gu":"\uc740\ud3c9\uad6c","dong":"\ubd88\uad112\ub3d9","household":"13,887","pop_total_male":"14,139","pop_total_female":"14,930","over_65":"5,769"},{"gu":"\uc740\ud3c9\uad6c","dong":"\uc751\uc5543\ub3d9","household":"12,698","pop_total_male":"12,584","pop_total_female":"13,218","over_65":"5,523"},{"gu":"\uc740\ud3c9\uad6c","dong":"\uc5ed\ucd0c\ub3d9","household":"20,795","pop_total_male":"22,576","pop_total_female":"25,142","over_65":"8,181"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\ucc9c\uc5f0\ub3d9","household":"8,164","pop_total_male":"8,794","pop_total_female":"9,675","over_65":"3,321"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\ud64d\uc81c1\ub3d9","household":"10,391","pop_total_male":"11,674","pop_total_female":"13,137","over_65":"4,413"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\ud64d\uc81c3\ub3d9","household":"7,103","pop_total_male":"7,852","pop_total_female":"8,303","over_65":"3,502"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\ud64d\uc81c2\ub3d9","household":"5,898","pop_total_male":"6,907","pop_total_female":"7,613","over_65":"2,666"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\ud64d\uc7401\ub3d9","household":"9,592","pop_total_male":"11,237","pop_total_female":"12,029","over_65":"4,452"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\ud64d\uc7402\ub3d9","household":"12,274","pop_total_male":"13,488","pop_total_female":"14,494","over_65":"4,979"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\ub0a8\uac00\uc88c1\ub3d9","household":"5,928","pop_total_male":"7,874","pop_total_female":"8,497","over_65":"2,123"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\ub0a8\uac00\uc88c2\ub3d9","household":"13,099","pop_total_male":"14,722","pop_total_female":"16,005","over_65":"4,686"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\ubd81\uac00\uc88c1\ub3d9","household":"6,987","pop_total_male":"9,079","pop_total_female":"9,730","over_65":"2,908"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\ubd81\uac00\uc88c2\ub3d9","household":"14,752","pop_total_male":"16,217","pop_total_female":"17,215","over_65":"6,150"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\ucda9\ud604\ub3d9","household":"9,183","pop_total_male":"8,777","pop_total_female":"9,521","over_65":"3,202"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\ubd81\uc544\ud604\ub3d9","household":"7,542","pop_total_male":"8,268","pop_total_female":"9,121","over_65":"2,330"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\uc2e0\ucd0c\ub3d9","household":"12,893","pop_total_male":"9,537","pop_total_female":"13,733","over_65":"2,209"},{"gu":"\uc11c\ub300\ubb38\uad6c","dong":"\uc5f0\ud76c\ub3d9","household":"19,517","pop_total_male":"19,495","pop_total_female":"21,230","over_65":"6,527"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\uc6a9\uac15\ub3d9","household":"9,197","pop_total_male":"10,577","pop_total_female":"11,718","over_65":"2,887"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\ub300\ud765\ub3d9","household":"8,216","pop_total_male":"7,357","pop_total_female":"8,396","over_65":"2,070"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\uc5fc\ub9ac\ub3d9","household":"5,658","pop_total_male":"6,173","pop_total_female":"6,938","over_65":"1,767"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\uc2e0\uc218\ub3d9","household":"10,214","pop_total_male":"11,528","pop_total_female":"12,268","over_65":"3,297"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\uc11c\uad50\ub3d9","household":"14,808","pop_total_male":"11,827","pop_total_female":"14,446","over_65":"3,398"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\ud569\uc815\ub3d9","household":"9,691","pop_total_male":"8,723","pop_total_female":"10,127","over_65":"2,661"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\ub9dd\uc6d01\ub3d9","household":"10,586","pop_total_male":"10,048","pop_total_female":"11,401","over_65":"3,386"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\ub9dd\uc6d02\ub3d9","household":"8,467","pop_total_male":"9,136","pop_total_female":"10,180","over_65":"2,999"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\uc5f0\ub0a8\ub3d9","household":"8,818","pop_total_male":"7,851","pop_total_female":"8,973","over_65":"2,514"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\uc131\uc0b01\ub3d9","household":"9,448","pop_total_male":"9,396","pop_total_female":"10,587","over_65":"2,920"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\uc131\uc0b02\ub3d9","household":"19,020","pop_total_male":"18,868","pop_total_female":"22,405","over_65":"6,038"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\uc0c1\uc554\ub3d9","household":"12,809","pop_total_male":"15,468","pop_total_female":"16,939","over_65":"3,883"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\ub3c4\ud654\ub3d9","household":"9,570","pop_total_male":"10,677","pop_total_female":"11,655","over_65":"3,682"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\uc11c\uac15\ub3d9","household":"11,696","pop_total_male":"12,169","pop_total_female":"13,694","over_65":"3,144"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\uacf5\ub355\ub3d9","household":"19,099","pop_total_male":"18,964","pop_total_female":"21,088","over_65":"5,990"},{"gu":"\ub9c8\ud3ec\uad6c","dong":"\uc544\ud604\ub3d9","household":"10,247","pop_total_male":"11,897","pop_total_female":"13,483","over_65":"3,058"},{"gu":"\uc591\ucc9c\uad6c","dong":"\ubaa91\ub3d9","household":"10,568","pop_total_male":"15,408","pop_total_female":"16,687","over_65":"3,027"},{"gu":"\uc591\ucc9c\uad6c","dong":"\ubaa92\ub3d9","household":"13,225","pop_total_male":"15,157","pop_total_female":"16,021","over_65":"3,973"},{"gu":"\uc591\ucc9c\uad6c","dong":"\ubaa93\ub3d9","household":"10,042","pop_total_male":"10,979","pop_total_female":"11,939","over_65":"3,159"},{"gu":"\uc591\ucc9c\uad6c","dong":"\ubaa94\ub3d9","household":"10,118","pop_total_male":"13,000","pop_total_female":"13,531","over_65":"3,126"},{"gu":"\uc591\ucc9c\uad6c","dong":"\uc2e0\uc6d41\ub3d9","household":"10,130","pop_total_male":"10,980","pop_total_female":"10,476","over_65":"3,964"},{"gu":"\uc591\ucc9c\uad6c","dong":"\uc2e0\uc6d42\ub3d9","household":"8,506","pop_total_male":"10,632","pop_total_female":"11,037","over_65":"3,705"},{"gu":"\uc591\ucc9c\uad6c","dong":"\uc2e0\uc6d43\ub3d9","household":"8,136","pop_total_male":"8,619","pop_total_female":"7,730","over_65":"2,896"},{"gu":"\uc591\ucc9c\uad6c","dong":"\uc2e0\uc6d44\ub3d9","household":"6,917","pop_total_male":"9,158","pop_total_female":"9,501","over_65":"3,055"},{"gu":"\uc591\ucc9c\uad6c","dong":"\uc2e0\uc6d45\ub3d9","household":"6,453","pop_total_male":"7,638","pop_total_female":"7,754","over_65":"2,349"},{"gu":"\uc591\ucc9c\uad6c","dong":"\uc2e0\uc6d46\ub3d9","household":"4,723","pop_total_male":"6,171","pop_total_female":"6,323","over_65":"1,566"},{"gu":"\uc591\ucc9c\uad6c","dong":"\uc2e0\uc6d47\ub3d9","household":"9,225","pop_total_male":"10,299","pop_total_female":"10,739","over_65":"4,189"},{"gu":"\uc591\ucc9c\uad6c","dong":"\uc2e0\uc8151\ub3d9","household":"7,206","pop_total_male":"10,371","pop_total_female":"10,854","over_65":"2,574"},{"gu":"\uc591\ucc9c\uad6c","dong":"\uc2e0\uc8152\ub3d9","household":"7,123","pop_total_male":"10,017","pop_total_female":"10,465","over_65":"2,509"},{"gu":"\uc591\ucc9c\uad6c","dong":"\uc2e0\uc8153\ub3d9","household":"17,913","pop_total_male":"23,163","pop_total_female":"24,337","over_65":"6,682"},{"gu":"\uc591\ucc9c\uad6c","dong":"\uc2e0\uc8156\ub3d9","household":"8,222","pop_total_male":"12,278","pop_total_female":"12,939","over_65":"2,559"},{"gu":"\uc591\ucc9c\uad6c","dong":"\uc2e0\uc8157\ub3d9","household":"11,567","pop_total_male":"14,717","pop_total_female":"15,665","over_65":"4,673"},{"gu":"\uc591\ucc9c\uad6c","dong":"\ubaa95\ub3d9","household":"13,572","pop_total_male":"21,123","pop_total_female":"21,522","over_65":"4,131"},{"gu":"\uc591\ucc9c\uad6c","dong":"\uc2e0\uc8154\ub3d9","household":"16,031","pop_total_male":"17,038","pop_total_female":"17,766","over_65":"5,687"},{"gu":"\uac15\uc11c\uad6c","dong":"\uc5fc\ucc3d\ub3d9","household":"15,757","pop_total_male":"20,597","pop_total_female":"21,662","over_65":"4,105"},{"gu":"\uac15\uc11c\uad6c","dong":"\ub4f1\ucd0c1\ub3d9","household":"12,463","pop_total_male":"11,169","pop_total_female":"12,600","over_65":"2,753"},{"gu":"\uac15\uc11c\uad6c","dong":"\ub4f1\ucd0c2\ub3d9","household":"8,762","pop_total_male":"10,578","pop_total_female":"10,998","over_65":"3,015"},{"gu":"\uac15\uc11c\uad6c","dong":"\ub4f1\ucd0c3\ub3d9","household":"14,985","pop_total_male":"15,357","pop_total_female":"16,851","over_65":"6,300"},{"gu":"\uac15\uc11c\uad6c","dong":"\ud654\uace1\ubcf8\ub3d9","household":"16,679","pop_total_male":"17,326","pop_total_female":"18,227","over_65":"4,685"},{"gu":"\uac15\uc11c\uad6c","dong":"\ud654\uace12\ub3d9","household":"8,231","pop_total_male":"9,290","pop_total_female":"9,829","over_65":"2,793"},{"gu":"\uac15\uc11c\uad6c","dong":"\ud654\uace13\ub3d9","household":"9,455","pop_total_male":"10,712","pop_total_female":"11,594","over_65":"3,869"},{"gu":"\uac15\uc11c\uad6c","dong":"\ud654\uace14\ub3d9","household":"9,695","pop_total_male":"10,637","pop_total_female":"11,121","over_65":"3,652"},{"gu":"\uac15\uc11c\uad6c","dong":"\ud654\uace16\ub3d9","household":"12,164","pop_total_male":"12,426","pop_total_female":"12,979","over_65":"3,753"},{"gu":"\uac15\uc11c\uad6c","dong":"\ud654\uace18\ub3d9","household":"11,784","pop_total_male":"12,551","pop_total_female":"13,604","over_65":"4,211"},{"gu":"\uac15\uc11c\uad6c","dong":"\uac00\uc5911\ub3d9","household":"19,497","pop_total_male":"15,854","pop_total_female":"18,333","over_65":"2,901"},{"gu":"\uac15\uc11c\uad6c","dong":"\uac00\uc5912\ub3d9","household":"8,112","pop_total_male":"7,081","pop_total_female":"7,880","over_65":"3,795"},{"gu":"\uac15\uc11c\uad6c","dong":"\uac00\uc5913\ub3d9","household":"7,929","pop_total_male":"7,482","pop_total_female":"8,494","over_65":"3,491"},{"gu":"\uac15\uc11c\uad6c","dong":"\ubc1c\uc0b01\ub3d9","household":"13,646","pop_total_male":"18,159","pop_total_female":"20,129","over_65":"4,564"},{"gu":"\uac15\uc11c\uad6c","dong":"\uacf5\ud56d\ub3d9","household":"12,780","pop_total_male":"14,398","pop_total_female":"13,618","over_65":"3,785"},{"gu":"\uac15\uc11c\uad6c","dong":"\ubc29\ud6541\ub3d9","household":"17,515","pop_total_male":"22,043","pop_total_female":"23,236","over_65":"6,331"},{"gu":"\uac15\uc11c\uad6c","dong":"\ubc29\ud6542\ub3d9","household":"11,628","pop_total_male":"11,755","pop_total_female":"12,016","over_65":"4,627"},{"gu":"\uac15\uc11c\uad6c","dong":"\ubc29\ud6543\ub3d9","household":"11,328","pop_total_male":"11,670","pop_total_female":"12,460","over_65":"4,874"},{"gu":"\uac15\uc11c\uad6c","dong":"\ud654\uace11\ub3d9","household":"26,704","pop_total_male":"26,331","pop_total_female":"27,829","over_65":"8,058"},{"gu":"\uac15\uc11c\uad6c","dong":"\uc6b0\uc7a5\uc0b0\ub3d9","household":"16,138","pop_total_male":"21,252","pop_total_female":"23,075","over_65":"5,470"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uc2e0\ub3c4\ub9bc\ub3d9","household":"13,425","pop_total_male":"17,982","pop_total_female":"18,722","over_65":"4,443"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uad6c\ub85c1\ub3d9","household":"8,346","pop_total_male":"10,791","pop_total_female":"11,140","over_65":"2,373"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uad6c\ub85c3\ub3d9","household":"13,178","pop_total_male":"13,312","pop_total_female":"12,667","over_65":"3,397"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uad6c\ub85c4\ub3d9","household":"10,626","pop_total_male":"13,088","pop_total_female":"12,774","over_65":"4,442"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uad6c\ub85c5\ub3d9","household":"14,646","pop_total_male":"16,274","pop_total_female":"16,892","over_65":"4,591"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uace0\ucc991\ub3d9","household":"9,596","pop_total_male":"11,971","pop_total_female":"11,995","over_65":"4,175"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uace0\ucc992\ub3d9","household":"11,612","pop_total_male":"14,111","pop_total_female":"14,304","over_65":"4,887"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uac1c\ubd092\ub3d9","household":"12,580","pop_total_male":"15,907","pop_total_female":"16,653","over_65":"5,999"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uac1c\ubd093\ub3d9","household":"8,911","pop_total_male":"10,718","pop_total_female":"11,181","over_65":"4,047"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uc624\ub9581\ub3d9","household":"11,610","pop_total_male":"11,472","pop_total_female":"11,952","over_65":"3,855"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uc218\uad81\ub3d9","household":"9,899","pop_total_male":"12,105","pop_total_female":"12,363","over_65":"4,121"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uac00\ub9ac\ubd09\ub3d9","household":"5,971","pop_total_male":"8,650","pop_total_female":"6,412","over_65":"2,128"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uad6c\ub85c2\ub3d9","household":"12,704","pop_total_male":"17,952","pop_total_female":"16,454","over_65":"5,794"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uac1c\ubd091\ub3d9","household":"13,849","pop_total_male":"16,562","pop_total_female":"16,466","over_65":"5,975"},{"gu":"\uad6c\ub85c\uad6c","dong":"\uc624\ub9582\ub3d9","household":"15,550","pop_total_male":"19,496","pop_total_female":"20,801","over_65":"6,655"},{"gu":"\uad6c\ub85c\uad6c","dong":"\ud56d\ub3d9","household":"5,864","pop_total_male":"7,660","pop_total_female":"7,880","over_65":"1,398"},{"gu":"\uae08\ucc9c\uad6c","dong":"\uac00\uc0b0\ub3d9","household":"14,456","pop_total_male":"13,886","pop_total_female":"10,944","over_65":"2,517"},{"gu":"\uae08\ucc9c\uad6c","dong":"\ub3c5\uc0b01\ub3d9","household":"21,047","pop_total_male":"23,311","pop_total_female":"21,501","over_65":"5,507"},{"gu":"\uae08\ucc9c\uad6c","dong":"\ub3c5\uc0b02\ub3d9","household":"9,304","pop_total_male":"10,732","pop_total_female":"10,306","over_65":"3,320"},{"gu":"\uae08\ucc9c\uad6c","dong":"\ub3c5\uc0b03\ub3d9","household":"12,455","pop_total_male":"15,115","pop_total_female":"14,236","over_65":"4,479"},{"gu":"\uae08\ucc9c\uad6c","dong":"\ub3c5\uc0b04\ub3d9","household":"7,665","pop_total_male":"9,137","pop_total_female":"8,864","over_65":"2,845"},{"gu":"\uae08\ucc9c\uad6c","dong":"\uc2dc\ud7651\ub3d9","household":"15,972","pop_total_male":"18,278","pop_total_female":"17,996","over_65":"5,999"},{"gu":"\uae08\ucc9c\uad6c","dong":"\uc2dc\ud7652\ub3d9","household":"8,424","pop_total_male":"10,819","pop_total_female":"11,497","over_65":"3,917"},{"gu":"\uae08\ucc9c\uad6c","dong":"\uc2dc\ud7653\ub3d9","household":"4,757","pop_total_male":"5,731","pop_total_female":"5,729","over_65":"2,240"},{"gu":"\uae08\ucc9c\uad6c","dong":"\uc2dc\ud7654\ub3d9","household":"9,117","pop_total_male":"10,849","pop_total_female":"11,028","over_65":"3,904"},{"gu":"\uae08\ucc9c\uad6c","dong":"\uc2dc\ud7655\ub3d9","household":"9,373","pop_total_male":"10,220","pop_total_female":"10,375","over_65":"4,222"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\uc5ec\uc758\ub3d9","household":"13,729","pop_total_male":"16,344","pop_total_female":"18,331","over_65":"6,066"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\ub2f9\uc0b01\ub3d9","household":"10,721","pop_total_male":"10,503","pop_total_female":"10,836","over_65":"3,297"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\ub2f9\uc0b02\ub3d9","household":"18,049","pop_total_male":"17,447","pop_total_female":"19,802","over_65":"4,495"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\uc591\ud3c91\ub3d9","household":"9,088","pop_total_male":"8,884","pop_total_female":"9,146","over_65":"2,459"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\uc591\ud3c92\ub3d9","household":"10,126","pop_total_male":"11,278","pop_total_female":"11,387","over_65":"2,461"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\uc2e0\uae381\ub3d9","household":"10,364","pop_total_male":"10,018","pop_total_female":"9,519","over_65":"3,341"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\uc2e0\uae383\ub3d9","household":"7,650","pop_total_male":"9,187","pop_total_female":"9,249","over_65":"3,032"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\uc2e0\uae384\ub3d9","household":"4,327","pop_total_male":"5,029","pop_total_female":"4,813","over_65":"1,873"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\uc2e0\uae385\ub3d9","household":"4,937","pop_total_male":"6,294","pop_total_female":"6,418","over_65":"2,039"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\uc2e0\uae386\ub3d9","household":"8,565","pop_total_male":"9,446","pop_total_female":"9,725","over_65":"3,164"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\uc2e0\uae387\ub3d9","household":"7,881","pop_total_male":"10,299","pop_total_female":"10,335","over_65":"2,344"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\ub300\ub9bc1\ub3d9","household":"6,379","pop_total_male":"8,218","pop_total_female":"7,800","over_65":"2,898"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\ub300\ub9bc2\ub3d9","household":"6,865","pop_total_male":"10,909","pop_total_female":"9,911","over_65":"3,005"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\ub300\ub9bc3\ub3d9","household":"10,453","pop_total_male":"14,346","pop_total_female":"13,629","over_65":"4,285"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\uc601\ub4f1\ud3ec\ubcf8\ub3d9","household":"10,228","pop_total_male":"12,540","pop_total_female":"11,764","over_65":"3,971"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\uc601\ub4f1\ud3ec\ub3d9","household":"18,003","pop_total_male":"15,017","pop_total_female":"12,745","over_65":"3,450"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\ub3c4\ub9bc\ub3d9","household":"9,384","pop_total_male":"10,776","pop_total_female":"10,475","over_65":"3,361"},{"gu":"\uc601\ub4f1\ud3ec\uad6c","dong":"\ubb38\ub798\ub3d9","household":"13,038","pop_total_male":"16,113","pop_total_female":"16,621","over_65":"4,530"},{"gu":"\ub3d9\uc791\uad6c","dong":"\ub178\ub7c9\uc9c42\ub3d9","household":"7,262","pop_total_male":"7,043","pop_total_female":"6,607","over_65":"2,696"},{"gu":"\ub3d9\uc791\uad6c","dong":"\uc0c1\ub3c41\ub3d9","household":"21,593","pop_total_male":"22,899","pop_total_female":"24,630","over_65":"6,768"},{"gu":"\ub3d9\uc791\uad6c","dong":"\uc0c1\ub3c42\ub3d9","household":"12,775","pop_total_male":"13,872","pop_total_female":"14,988","over_65":"4,342"},{"gu":"\ub3d9\uc791\uad6c","dong":"\uc0c1\ub3c43\ub3d9","household":"12,046","pop_total_male":"12,355","pop_total_female":"13,443","over_65":"4,244"},{"gu":"\ub3d9\uc791\uad6c","dong":"\uc0c1\ub3c44\ub3d9","household":"13,712","pop_total_male":"14,429","pop_total_female":"15,294","over_65":"4,844"},{"gu":"\ub3d9\uc791\uad6c","dong":"\uc0ac\ub2f91\ub3d9","household":"13,246","pop_total_male":"11,364","pop_total_female":"12,567","over_65":"3,637"},{"gu":"\ub3d9\uc791\uad6c","dong":"\uc0ac\ub2f93\ub3d9","household":"10,541","pop_total_male":"12,395","pop_total_female":"13,185","over_65":"4,292"},{"gu":"\ub3d9\uc791\uad6c","dong":"\uc0ac\ub2f94\ub3d9","household":"7,153","pop_total_male":"7,088","pop_total_female":"7,731","over_65":"2,549"},{"gu":"\ub3d9\uc791\uad6c","dong":"\uc0ac\ub2f95\ub3d9","household":"6,503","pop_total_male":"7,107","pop_total_female":"7,555","over_65":"2,200"},{"gu":"\ub3d9\uc791\uad6c","dong":"\ub300\ubc29\ub3d9","household":"17,229","pop_total_male":"18,842","pop_total_female":"20,841","over_65":"5,514"},{"gu":"\ub3d9\uc791\uad6c","dong":"\uc2e0\ub300\ubc291\ub3d9","household":"10,116","pop_total_male":"12,842","pop_total_female":"13,462","over_65":"3,680"},{"gu":"\ub3d9\uc791\uad6c","dong":"\uc2e0\ub300\ubc292\ub3d9","household":"9,424","pop_total_male":"9,799","pop_total_female":"10,747","over_65":"2,972"},{"gu":"\ub3d9\uc791\uad6c","dong":"\ud751\uc11d\ub3d9","household":"14,397","pop_total_male":"16,740","pop_total_female":"18,252","over_65":"5,617"},{"gu":"\ub3d9\uc791\uad6c","dong":"\ub178\ub7c9\uc9c41\ub3d9","household":"15,596","pop_total_male":"16,217","pop_total_female":"16,432","over_65":"5,569"},{"gu":"\ub3d9\uc791\uad6c","dong":"\uc0ac\ub2f92\ub3d9","household":"11,944","pop_total_male":"13,487","pop_total_female":"14,563","over_65":"5,115"},{"gu":"\uad00\uc545\uad6c","dong":"\ubcf4\ub77c\ub9e4\ub3d9","household":"12,466","pop_total_male":"12,677","pop_total_female":"13,179","over_65":"4,300"},{"gu":"\uad00\uc545\uad6c","dong":"\uccad\ub9bc\ub3d9","household":"6,566","pop_total_male":"7,818","pop_total_female":"8,189","over_65":"2,683"},{"gu":"\uad00\uc545\uad6c","dong":"\ud589\uc6b4\ub3d9","household":"17,453","pop_total_male":"14,607","pop_total_female":"15,618","over_65":"4,245"},{"gu":"\uad00\uc545\uad6c","dong":"\ub099\uc131\ub300\ub3d9","household":"11,105","pop_total_male":"8,966","pop_total_female":"8,874","over_65":"1,959"},{"gu":"\uad00\uc545\uad6c","dong":"\uc911\uc559\ub3d9","household":"9,724","pop_total_male":"7,653","pop_total_female":"8,412","over_65":"2,368"},{"gu":"\uad00\uc545\uad6c","dong":"\uc778\ud5cc\ub3d9","household":"14,245","pop_total_male":"13,142","pop_total_female":"13,796","over_65":"3,894"},{"gu":"\uad00\uc545\uad6c","dong":"\ub0a8\ud604\ub3d9","household":"9,478","pop_total_male":"9,065","pop_total_female":"9,749","over_65":"2,666"},{"gu":"\uad00\uc545\uad6c","dong":"\uc11c\uc6d0\ub3d9","household":"14,209","pop_total_male":"12,366","pop_total_female":"11,683","over_65":"3,218"},{"gu":"\uad00\uc545\uad6c","dong":"\uc2e0\uc6d0\ub3d9","household":"10,793","pop_total_male":"9,822","pop_total_female":"9,825","over_65":"3,186"},{"gu":"\uad00\uc545\uad6c","dong":"\uc11c\ub9bc\ub3d9","household":"14,453","pop_total_male":"13,359","pop_total_female":"11,081","over_65":"3,416"},{"gu":"\uad00\uc545\uad6c","dong":"\uc2e0\uc0ac\ub3d9","household":"13,607","pop_total_male":"13,081","pop_total_female":"12,895","over_65":"3,493"},{"gu":"\uad00\uc545\uad6c","dong":"\uc2e0\ub9bc\ub3d9","household":"17,212","pop_total_male":"11,828","pop_total_female":"11,025","over_65":"1,959"},{"gu":"\uad00\uc545\uad6c","dong":"\ub09c\ud5a5\ub3d9","household":"6,434","pop_total_male":"7,963","pop_total_female":"8,208","over_65":"2,729"},{"gu":"\uad00\uc545\uad6c","dong":"\uc870\uc6d0\ub3d9","household":"10,541","pop_total_male":"9,968","pop_total_female":"9,563","over_65":"2,758"},{"gu":"\uad00\uc545\uad6c","dong":"\ub300\ud559\ub3d9","household":"16,191","pop_total_male":"14,796","pop_total_female":"10,091","over_65":"2,788"},{"gu":"\uad00\uc545\uad6c","dong":"\uc740\ucc9c\ub3d9","household":"16,075","pop_total_male":"17,118","pop_total_female":"17,877","over_65":"5,655"},{"gu":"\uad00\uc545\uad6c","dong":"\uc131\ud604\ub3d9","household":"12,492","pop_total_male":"14,851","pop_total_female":"15,852","over_65":"5,254"},{"gu":"\uad00\uc545\uad6c","dong":"\uccad\ub8e1\ub3d9","household":"22,094","pop_total_male":"17,124","pop_total_female":"18,642","over_65":"4,336"},{"gu":"\uad00\uc545\uad6c","dong":"\ub09c\uace1\ub3d9","household":"12,971","pop_total_male":"14,266","pop_total_female":"14,148","over_65":"5,189"},{"gu":"\uad00\uc545\uad6c","dong":"\uc0bc\uc131\ub3d9","household":"11,429","pop_total_male":"12,430","pop_total_female":"12,411","over_65":"5,713"},{"gu":"\uad00\uc545\uad6c","dong":"\ubbf8\uc131\ub3d9","household":"14,177","pop_total_male":"15,840","pop_total_female":"16,460","over_65":"5,532"},{"gu":"\uc11c\ucd08\uad6c","dong":"\uc11c\ucd081\ub3d9","household":"9,345","pop_total_male":"10,316","pop_total_female":"11,087","over_65":"2,994"},{"gu":"\uc11c\ucd08\uad6c","dong":"\uc11c\ucd082\ub3d9","household":"8,575","pop_total_male":"9,018","pop_total_female":"9,935","over_65":"2,166"},{"gu":"\uc11c\ucd08\uad6c","dong":"\uc11c\ucd083\ub3d9","household":"13,880","pop_total_male":"15,128","pop_total_female":"16,030","over_65":"4,504"},{"gu":"\uc11c\ucd08\uad6c","dong":"\uc11c\ucd084\ub3d9","household":"11,060","pop_total_male":"15,572","pop_total_female":"16,403","over_65":"4,000"},{"gu":"\uc11c\ucd08\uad6c","dong":"\uc7a0\uc6d0\ub3d9","household":"13,667","pop_total_male":"16,053","pop_total_female":"17,735","over_65":"3,898"},{"gu":"\uc11c\ucd08\uad6c","dong":"\ubc18\ud3ec\ubcf8\ub3d9","household":"4,136","pop_total_male":"5,750","pop_total_female":"6,357","over_65":"1,936"},{"gu":"\uc11c\ucd08\uad6c","dong":"\ubc18\ud3ec1\ub3d9","household":"14,389","pop_total_male":"15,899","pop_total_female":"17,082","over_65":"3,423"},{"gu":"\uc11c\ucd08\uad6c","dong":"\ubc18\ud3ec2\ub3d9","household":"5,123","pop_total_male":"7,800","pop_total_female":"8,527","over_65":"1,899"},{"gu":"\uc11c\ucd08\uad6c","dong":"\ubc18\ud3ec3\ub3d9","household":"7,525","pop_total_male":"10,276","pop_total_female":"11,465","over_65":"2,722"},{"gu":"\uc11c\ucd08\uad6c","dong":"\ubc18\ud3ec4\ub3d9","household":"7,319","pop_total_male":"9,561","pop_total_female":"10,587","over_65":"2,767"},{"gu":"\uc11c\ucd08\uad6c","dong":"\ubc29\ubc30\ubcf8\ub3d9","household":"7,964","pop_total_male":"9,920","pop_total_female":"11,504","over_65":"2,984"},{"gu":"\uc11c\ucd08\uad6c","dong":"\ubc29\ubc301\ub3d9","household":"7,720","pop_total_male":"8,273","pop_total_female":"9,386","over_65":"2,778"},{"gu":"\uc11c\ucd08\uad6c","dong":"\ubc29\ubc302\ub3d9","household":"8,707","pop_total_male":"9,691","pop_total_female":"10,937","over_65":"3,433"},{"gu":"\uc11c\ucd08\uad6c","dong":"\ubc29\ubc303\ub3d9","household":"8,366","pop_total_male":"10,578","pop_total_female":"11,360","over_65":"3,651"},{"gu":"\uc11c\ucd08\uad6c","dong":"\ubc29\ubc304\ub3d9","household":"9,796","pop_total_male":"10,997","pop_total_female":"13,032","over_65":"3,331"},{"gu":"\uc11c\ucd08\uad6c","dong":"\uc591\uc7ac1\ub3d9","household":"18,283","pop_total_male":"21,779","pop_total_female":"23,707","over_65":"6,639"},{"gu":"\uc11c\ucd08\uad6c","dong":"\uc591\uc7ac2\ub3d9","household":"10,808","pop_total_male":"11,540","pop_total_female":"11,390","over_65":"2,816"},{"gu":"\uc11c\ucd08\uad6c","dong":"\ub0b4\uace1\ub3d9","household":"7,335","pop_total_male":"8,944","pop_total_female":"9,443","over_65":"3,122"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uc2e0\uc0ac\ub3d9","household":"7,391","pop_total_male":"8,040","pop_total_female":"9,230","over_65":"2,909"},{"gu":"\uac15\ub0a8\uad6c","dong":"\ub17c\ud6041\ub3d9","household":"14,443","pop_total_male":"11,205","pop_total_female":"12,711","over_65":"2,942"},{"gu":"\uac15\ub0a8\uad6c","dong":"\ub17c\ud6042\ub3d9","household":"11,440","pop_total_male":"10,129","pop_total_female":"11,722","over_65":"3,056"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uc0bc\uc1311\ub3d9","household":"6,042","pop_total_male":"7,454","pop_total_female":"7,470","over_65":"2,187"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uc0bc\uc1312\ub3d9","household":"13,490","pop_total_male":"14,542","pop_total_female":"15,992","over_65":"3,344"},{"gu":"\uac15\ub0a8\uad6c","dong":"\ub300\uce581\ub3d9","household":"7,394","pop_total_male":"12,612","pop_total_female":"12,529","over_65":"2,283"},{"gu":"\uac15\ub0a8\uad6c","dong":"\ub300\uce584\ub3d9","household":"10,216","pop_total_male":"9,786","pop_total_female":"10,958","over_65":"2,002"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uc5ed\uc0bc1\ub3d9","household":"23,850","pop_total_male":"17,756","pop_total_female":"19,165","over_65":"3,597"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uc5ed\uc0bc2\ub3d9","household":"15,690","pop_total_male":"17,604","pop_total_female":"19,953","over_65":"3,576"},{"gu":"\uac15\ub0a8\uad6c","dong":"\ub3c4\uace11\ub3d9","household":"8,652","pop_total_male":"10,672","pop_total_female":"11,838","over_65":"2,864"},{"gu":"\uac15\ub0a8\uad6c","dong":"\ub3c4\uace12\ub3d9","household":"11,843","pop_total_male":"15,973","pop_total_female":"18,406","over_65":"4,588"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uac1c\ud3ec1\ub3d9","household":"2,713","pop_total_male":"3,313","pop_total_female":"3,540","over_65":"1,547"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uac1c\ud3ec4\ub3d9","household":"7,768","pop_total_male":"8,913","pop_total_female":"9,303","over_65":"2,382"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uc77c\uc6d0\ubcf8\ub3d9","household":"8,160","pop_total_male":"11,928","pop_total_female":"12,281","over_65":"2,740"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uc77c\uc6d01\ub3d9","household":"7,499","pop_total_male":"7,893","pop_total_female":"8,285","over_65":"3,102"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uc77c\uc6d02\ub3d9","household":"7,392","pop_total_male":"8,698","pop_total_female":"9,319","over_65":"3,100"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uc218\uc11c\ub3d9","household":"7,881","pop_total_male":"7,157","pop_total_female":"8,532","over_65":"4,290"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uc138\uace1\ub3d9","household":"17,978","pop_total_male":"21,407","pop_total_female":"23,590","over_65":"6,254"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uc555\uad6c\uc815\ub3d9","household":"10,723","pop_total_male":"12,805","pop_total_female":"14,999","over_65":"5,002"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uccad\ub2f4\ub3d9","household":"11,891","pop_total_male":"12,932","pop_total_female":"14,666","over_65":"3,787"},{"gu":"\uac15\ub0a8\uad6c","dong":"\ub300\uce582\ub3d9","household":"12,950","pop_total_male":"19,474","pop_total_female":"18,836","over_65":"4,518"},{"gu":"\uac15\ub0a8\uad6c","dong":"\uac1c\ud3ec2\ub3d9","household":"8,078","pop_total_male":"10,894","pop_total_female":"11,646","over_65":"3,027"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\ud48d\ub0a91\ub3d9","household":"6,440","pop_total_male":"7,422","pop_total_female":"7,619","over_65":"2,767"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\ud48d\ub0a92\ub3d9","household":"11,102","pop_total_male":"12,327","pop_total_female":"13,629","over_65":"3,590"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uac70\uc5ec1\ub3d9","household":"5,566","pop_total_male":"6,709","pop_total_female":"6,474","over_65":"2,279"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uac70\uc5ec2\ub3d9","household":"7,204","pop_total_male":"8,217","pop_total_female":"8,562","over_65":"3,107"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\ub9c8\ucc9c1\ub3d9","household":"9,036","pop_total_male":"10,427","pop_total_female":"10,028","over_65":"4,108"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\ub9c8\ucc9c2\ub3d9","household":"8,823","pop_total_male":"10,180","pop_total_female":"9,888","over_65":"3,978"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\ubc29\uc7741\ub3d9","household":"6,306","pop_total_male":"7,925","pop_total_female":"8,536","over_65":"2,095"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\ubc29\uc7742\ub3d9","household":"14,267","pop_total_male":"12,586","pop_total_female":"14,077","over_65":"3,379"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc624\ub95c\ub3d9","household":"5,958","pop_total_male":"9,203","pop_total_female":"9,505","over_65":"2,516"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc624\uae08\ub3d9","household":"15,960","pop_total_male":"19,825","pop_total_female":"21,016","over_65":"5,946"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc1a1\ud30c1\ub3d9","household":"12,450","pop_total_male":"12,080","pop_total_female":"13,603","over_65":"3,313"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc1a1\ud30c2\ub3d9","household":"7,538","pop_total_male":"10,018","pop_total_female":"10,778","over_65":"2,775"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc11d\ucd0c\ub3d9","household":"17,093","pop_total_male":"16,141","pop_total_female":"17,686","over_65":"4,307"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc0bc\uc804\ub3d9","household":"16,325","pop_total_male":"15,260","pop_total_female":"16,960","over_65":"3,834"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uac00\ub77d\ubcf8\ub3d9","household":"11,962","pop_total_male":"13,744","pop_total_female":"13,971","over_65":"3,523"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uac00\ub77d1\ub3d9","household":"9,919","pop_total_male":"13,653","pop_total_female":"14,412","over_65":"2,937"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uac00\ub77d2\ub3d9","household":"12,339","pop_total_male":"16,447","pop_total_female":"17,056","over_65":"3,946"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\ubb38\uc8151\ub3d9","household":"8,569","pop_total_male":"10,442","pop_total_female":"10,792","over_65":"2,838"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\ubb38\uc8152\ub3d9","household":"15,575","pop_total_male":"13,878","pop_total_female":"16,109","over_65":"3,759"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc7a0\uc2e4\ubcf8\ub3d9","household":"15,386","pop_total_male":"13,886","pop_total_female":"15,522","over_65":"3,632"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc7a0\uc2e44\ub3d9","household":"7,454","pop_total_male":"10,643","pop_total_female":"11,420","over_65":"2,652"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc7a0\uc2e46\ub3d9","household":"5,950","pop_total_male":"8,307","pop_total_female":"9,158","over_65":"2,673"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc7a0\uc2e47\ub3d9","household":"3,475","pop_total_male":"4,693","pop_total_female":"5,395","over_65":"2,059"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc7a0\uc2e42\ub3d9","household":"11,964","pop_total_male":"17,569","pop_total_female":"19,143","over_65":"3,326"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc7a0\uc2e43\ub3d9","household":"12,176","pop_total_male":"17,048","pop_total_female":"18,732","over_65":"5,254"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc7a5\uc9c0\ub3d9","household":"12,268","pop_total_male":"14,990","pop_total_female":"16,032","over_65":"4,094"},{"gu":"\uc1a1\ud30c\uad6c","dong":"\uc704\ub840\ub3d9","household":"9,030","pop_total_male":"13,763","pop_total_female":"14,581","over_65":"2,013"},{"gu":"\uac15\ub3d9\uad6c","dong":"\uac15\uc77c\ub3d9","household":"11,253","pop_total_male":"15,383","pop_total_female":"16,483","over_65":"4,686"},{"gu":"\uac15\ub3d9\uad6c","dong":"\uc0c1\uc77c\ub3d9","household":"11,349","pop_total_male":"16,137","pop_total_female":"16,487","over_65":"3,473"},{"gu":"\uac15\ub3d9\uad6c","dong":"\uba85\uc77c1\ub3d9","household":"10,037","pop_total_male":"12,976","pop_total_female":"13,574","over_65":"3,732"},{"gu":"\uac15\ub3d9\uad6c","dong":"\uba85\uc77c2\ub3d9","household":"5,981","pop_total_male":"8,625","pop_total_female":"8,876","over_65":"2,372"},{"gu":"\uac15\ub3d9\uad6c","dong":"\uace0\ub3551\ub3d9","household":"8,938","pop_total_male":"13,494","pop_total_female":"13,042","over_65":"2,732"},{"gu":"\uac15\ub3d9\uad6c","dong":"\uace0\ub3552\ub3d9","household":"8,146","pop_total_male":"10,829","pop_total_female":"10,477","over_65":"2,619"},{"gu":"\uac15\ub3d9\uad6c","dong":"\uc554\uc0ac2\ub3d9","household":"6,382","pop_total_male":"7,583","pop_total_female":"8,064","over_65":"2,285"},{"gu":"\uac15\ub3d9\uad6c","dong":"\uc554\uc0ac3\ub3d9","household":"6,352","pop_total_male":"9,006","pop_total_female":"9,432","over_65":"2,456"},{"gu":"\uac15\ub3d9\uad6c","dong":"\ucc9c\ud6381\ub3d9","household":"12,862","pop_total_male":"13,782","pop_total_female":"14,259","over_65":"4,930"},{"gu":"\uac15\ub3d9\uad6c","dong":"\ucc9c\ud6383\ub3d9","household":"13,759","pop_total_male":"13,370","pop_total_female":"13,933","over_65":"4,501"},{"gu":"\uac15\ub3d9\uad6c","dong":"\uc131\ub0b41\ub3d9","household":"8,169","pop_total_male":"9,869","pop_total_female":"10,534","over_65":"2,900"},{"gu":"\uac15\ub3d9\uad6c","dong":"\uc131\ub0b42\ub3d9","household":"12,759","pop_total_male":"12,344","pop_total_female":"12,752","over_65":"4,139"},{"gu":"\uac15\ub3d9\uad6c","dong":"\uc131\ub0b43\ub3d9","household":"10,498","pop_total_male":"11,713","pop_total_female":"12,111","over_65":"3,594"},{"gu":"\uac15\ub3d9\uad6c","dong":"\ub454\ucd0c1\ub3d9","household":"161","pop_total_male":"130","pop_total_female":"144","over_65":"96"},{"gu":"\uac15\ub3d9\uad6c","dong":"\ub454\ucd0c2\ub3d9","household":"11,234","pop_total_male":"13,475","pop_total_female":"13,817","over_65":"4,111"},{"gu":"\uac15\ub3d9\uad6c","dong":"\uc554\uc0ac1\ub3d9","household":"16,179","pop_total_male":"17,927","pop_total_female":"18,327","over_65":"5,796"},{"gu":"\uac15\ub3d9\uad6c","dong":"\ucc9c\ud6382\ub3d9","household":"17,754","pop_total_male":"17,696","pop_total_female":"17,946","over_65":"5,875"},{"gu":"\uac15\ub3d9\uad6c","dong":"\uae38\ub3d9","household":"21,282","pop_total_male":"22,903","pop_total_female":"24,047","over_65":"7,445"}]

gu_population = {}  
for item in data:   #구와 구의 인구수를 딕셔너리로 엮기
    gu_population[item["gu"]] = gu_population.get(item['gu'],0) + int( "".join(item["pop_total_male"].split(",")) ) + int( "".join(item["pop_total_female"].split(",")) )   #키 값을 구 이름으로 놓고, 밸유값에는 인구를 누적시킨다.

region_list = list(gu_population.keys())
print(region_list)

['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구', '도봉구', '노원구', '은평구', '서대문구', '마포구', '양천구', '강서구', '구로구', '금천구', '영등포구', '동작구', '관악구', '서초구', '강남구', '송파구', '강동구']

In [16]:
#치과
#url 바꿔가면서 찾기
hospital_number = {}
hospital_review_number_mean = {}
population_per_hospital = {}

for region in region_list:
    url = f"https://www.modoodoc.com/q/?search_query={region}%20치과"
    driver = webdriver.Chrome('./chromedriver/chromedriver.exe')
    driver.implicitly_wait(2)
    driver.get(url)
    search_result = int(driver.find_element_by_class_name('color49').text[5:-1])
    hospital_number[region] = search_result
    
    req = requests.get(url)   #리뷰수
    html = req.text
    soup = BeautifulSoup(html, "html.parser")
    review_list = soup.find_all(attrs={'class':"review-count-box ml-1"})
    striped_list = [(i.text).strip() for i in review_list]
    review_number_list = [int(j[8:-1]) for j in striped_list]
    number_mean = sum(review_number_list) / len(review_number_list)
    hospital_review_number_mean[region] = number_mean
    
    driver.quit()  # 창 닫기
    
for item in region_list:    # 인구비율
    population_per_hospital[item] = gu_population[item]//hospital_number[item]

    
# 일단 진료과목별로 저장해 두기
dental_number = hospital_number
dental_review = hospital_review_number_mean
dental_population = population_per_hospital

#출력

dental_data_all = { "지역구":region_list, "치과 수": list(hospital_number.values()) , "치과 하나당 인구수":list(population_per_hospital.values()) ,"상위권 리뷰수":list(hospital_review_number_mean.values())}

dental_data = pd.DataFrame(dental_data_all)
dental_data

     지역구  치과 수  치과 하나당 인구수  상위권 리뷰수
0    종로구   195         823    17.95
1     중구   707         192    17.65
2    용산구    96        2555     9.15
3    성동구   156        1954    11.40
4    광진구   194        1875    16.00
5   동대문구   179        2013    15.95
6    중랑구   165        2420    10.35
7    성북구   163        2774    15.15
8    강북구   151        2088    14.55
9    도봉구   129        2571     7.55
10   노원구   227        2348    14.45
11   은평구   209        2315    12.55
12  서대문구   156        2078    25.10
13   마포구   235        1638    26.95
14   양천구   233        1982    13.50
15   강서구   325        1825    14.15
16   구로구   175        2495    12.80
17   금천구   120        2087     9.00
18  영등포구   278        1457    16.35
19   동작구   226        1799    17.40
20   관악구   251        2057    44.90
21   서초구   521         831    23.50
22   강남구   804         679    25.50
23   송파구   391        1734    21.55
24   강동구   282        1636    10.05

In [17]:
#피부과
#url 바꿔가면서 찾기
hospital_number = {}
hospital_review_number_mean = {}
population_per_hospital = {}

for region in region_list:
    url = f"https://www.modoodoc.com/q/?search_query={region}%20피부과"
    driver = webdriver.Chrome('./chromedriver/chromedriver.exe')
    driver.implicitly_wait(2)
    driver.get(url)
    search_result = int(driver.find_element_by_class_name('color49').text[5:-1])
    hospital_number[region] = search_result
    
    req = requests.get(url)   #리뷰수
    html = req.text
    soup = BeautifulSoup(html, "html.parser")
    review_list = soup.find_all(attrs={'class':"review-count-box ml-1"})
    striped_list = [(i.text).strip() for i in review_list]
    review_number_list = [int(j[8:-1]) for j in striped_list]
    number_mean = sum(review_number_list) / len(review_number_list)
    hospital_review_number_mean[region] = number_mean
    
    driver.quit()  # 창 닫기
    
for item in region_list:    # 인구비율
    population_per_hospital[item] = gu_population[item]//hospital_number[item]

    
    
# 일단 진료과목별로 저장해 두기
dermatic_number = hospital_number
dermatic_review = hospital_review_number_mean
dermatic_population = population_per_hospital

# 출력

dermatic_data_all = { "지역구":region_list, "피부과 수": list(hospital_number.values()) , "피부과 하나당 인구수":list(population_per_hospital.values()),"상위권 리뷰수":list(hospital_review_number_mean.values()) }

dermatic_data = pd.DataFrame(dermatic_data_all)
dermatic_data

     지역구  피부과 수  피부과 하나당 인구수  상위권 리뷰수
0    종로구     47         3415    17.15
1     중구    169          804    23.15
2    용산구     45         5452    10.75
3    성동구     35         8710    19.60
4    광진구     62         5869    22.50
5   동대문구     31        11625    15.65
6    중랑구     46         8682    12.95
7    성북구     52         8697    12.55
8    강북구     42         7509    12.15
9    도봉구     21        15797     7.25
10   노원구     67         7955    22.20
11   은평구     57         8490    18.25
12  서대문구     54         6004    20.45
13   마포구    130         2961    38.55
14   양천구     55         8400    17.45
15   강서구     93         6378    24.90
16   구로구     62         7043    22.25
17   금천구     21        11931     8.55
18  영등포구     69         5871    21.70
19   동작구     57         7136    22.15
20   관악구     62         8327    28.00
21   서초구    253         1711    47.80
22   강남구    779          701    58.90
23   송파구    123         5512    25.95
24   강동구     65         7100    21.75

In [18]:
#안과
#url 바꿔가면서 찾기
hospital_number = {}
hospital_review_number_mean = {}
population_per_hospital = {}

for region in region_list:
    url = f"https://www.modoodoc.com/q/?search_query={region}%20안과"
    driver = webdriver.Chrome('./chromedriver/chromedriver.exe')
    driver.implicitly_wait(2)
    driver.get(url)
    search_result = int(driver.find_element_by_class_name('color49').text[5:-1])
    hospital_number[region] = search_result
    
    req = requests.get(url)   #리뷰수
    html = req.text
    soup = BeautifulSoup(html, "html.parser")
    review_list = soup.find_all(attrs={'class':"review-count-box ml-1"})
    striped_list = [(i.text).strip() for i in review_list]
    review_number_list = [int(j[8:-1]) for j in striped_list]
    number_mean = sum(review_number_list) / len(review_number_list)
    hospital_review_number_mean[region] = number_mean
    
    driver.quit()  # 창 닫기
    
for item in region_list:    # 인구비율
    population_per_hospital[item] = gu_population[item]//hospital_number[item]

    
# 일단 진료과목별로 저장해 두기
ophthalmic_number = hospital_number
ophthalmic_review = hospital_review_number_mean
ophthalmic_population = population_per_hospital

# 출력

ophthalmic_data_all = { "지역구":region_list, "안과 수": list(hospital_number.values()) , "안과 하나당 인구수":list(population_per_hospital.values()) ,"상위권 리뷰수":list(hospital_review_number_mean.values())}

ophthalmic_data = pd.DataFrame(ophthalmic_data_all)
ophthalmic_data

     지역구  안과 수  안과 하나당 인구수    상위권 리뷰수
0    종로구    23        6979  14.450000
1     중구   113        1203  10.500000
2    용산구    14       17525   8.214286
3    성동구    15       20323  12.600000
4    광진구    16       22745  14.312500
5   동대문구    18       20021   7.777778
6    중랑구    14       28529  11.642857
7    성북구    21       21537  10.450000
8    강북구    22       14336   8.400000
9    도봉구    15       22116   6.666667
10   노원구    41       13001  11.700000
11   은평구    23       21040  10.750000
12  서대문구    16       20264  14.187500
13   마포구    21       18331  18.400000
14   양천구    16       28877  12.625000
15   강서구    49       12106  13.150000
16   구로구    21       20795  10.850000
17   금천구    10       25055  16.800000
18  영등포구    88        4604  10.850000
19   동작구    17       23928  13.764706
20   관악구    25       20652  15.600000
21   서초구   102        4245  21.050000
22   강남구   177        3085  19.600000
23   송파구    48       14126  16.050000
24   강동구    41       11257  10.000000

In [21]:
#성형외과
#url 바꿔가면서 찾기
hospital_number = {}
hospital_review_number_mean = {}
population_per_hospital = {}

for region in region_list:
    url = f"https://www.modoodoc.com/q/?search_query={region}%20성형외과"
    driver = webdriver.Chrome('./chromedriver/chromedriver.exe')
    driver.implicitly_wait(2)
    driver.get(url)
    search_result = int(driver.find_element_by_class_name('color49').text[5:-1])
    hospital_number[region] = search_result
    
    req = requests.get(url)
    html = req.text
    soup = BeautifulSoup(html, "html.parser")
    review_list = soup.find_all(attrs={'class':"review-count-box ml-1"})
    striped_list = [(i.text).strip() for i in review_list]
    review_number_list = [int(j[8:-1]) for j in striped_list]
    number_mean = sum(review_number_list) / len(review_number_list)
    hospital_review_number_mean[region] = number_mean
    
    driver.quit()  # 창 닫기
    
for item in region_list:    
    population_per_hospital[item] = gu_population[item]//hospital_number[item]

    
# 일단 진료과목별로 저장해 두기
cosmetic_number = hospital_number
cosmetic_review = hospital_review_number_mean
cosmetic_population = population_per_hospital

# 출력

cosmetic_data_all = { "지역구":region_list, "성형외과 수": list(hospital_number.values()) , "성형외과 하나당 인구수":list(population_per_hospital.values()) ,"상위권 리뷰수":list(hospital_review_number_mean.values())}

cosmetic_data = pd.DataFrame(cosmetic_data_all)
cosmetic_data

     지역구  성형외과 수  성형외과 하나당 인구수    상위권 리뷰수
0    종로구       5         32104   2.200000
1     중구     131          1038   1.950000
2    용산구       3         81787   3.000000
3    성동구       5         60970   3.200000
4    광진구       8         45490   2.125000
5   동대문구       9         40042   1.000000
6    중랑구       3        133138   0.000000
7    성북구       4        113072   0.750000
8    강북구       7         45056   1.571429
9    도봉구       2        165872   0.000000
10   노원구      17         31355   0.705882
11   은평구       7         69134   0.428571
12  서대문구       7         46317   3.714286
13   마포구      18         21386   5.111111
14   양천구       8         57754   0.375000
15   강서구      16         37075   1.562500
16   구로구       4        109176   0.750000
17   금천구       1        250554   0.000000
18  영등포구      11         36832   4.000000
19   동작구       5         81355   1.000000
20   관악구      13         39716   0.769231
21   서초구     237          1827  15.700000
22   강남구    1238           441  15.800000
23   송파구      18         37670   1.111111
24   강동구      12         38462   0.833333

In [22]:
#내과
#url 바꿔가면서 찾기
hospital_number = {}
hospital_review_number_mean = {}
population_per_hospital = {}

for region in region_list:
    url = f"https://www.modoodoc.com/q/?search_query={region}%20내과"
    driver = webdriver.Chrome('./chromedriver/chromedriver.exe')
    driver.implicitly_wait(2)
    driver.get(url)
    search_result = int(driver.find_element_by_class_name('color49').text[5:-1])
    hospital_number[region] = search_result
    
    req = requests.get(url)
    html = req.text
    soup = BeautifulSoup(html, "html.parser")
    review_list = soup.find_all(attrs={'class':"review-count-box ml-1"})
    striped_list = [(i.text).strip() for i in review_list]
    review_number_list = [int(j[8:-1]) for j in striped_list]
    number_mean = sum(review_number_list) / len(review_number_list)
    hospital_review_number_mean[region] = number_mean
    
    driver.quit()  # 창 닫기
    
for item in region_list:   
    population_per_hospital[item] = gu_population[item]//hospital_number[item]

    
# 일단 진료과목별로 저장해 두기
internel_number = hospital_number
internel_review = hospital_review_number_mean
internel_population = population_per_hospital

# 출력

internel_data_all = { "지역구":region_list, "내과 수": list(hospital_number.values()) , "내과 하나당 인구수":list(population_per_hospital.values()) ,"상위권 리뷰수":list(hospital_review_number_mean.values())}

internel_data = pd.DataFrame(internel_data_all)
internel_data

     지역구  내과 수  내과 하나당 인구수  상위권 리뷰수
0    종로구    44        3648     6.55
1     중구   358         379     7.25
2    용산구    60        4089     4.65
3    성동구    63        4838     5.70
4    광진구    78        4665     7.65
5   동대문구    89        4049     4.90
6    중랑구    88        4538     4.10
7    성북구    95        4760     6.20
8    강북구   104        3032     2.90
9    도봉구    61        5438     3.20
10   노원구    96        5552     4.85
11   은평구   107        4522     5.50
12  서대문구    50        6484     5.35
13   마포구   114        3376     9.65
14   양천구    82        5634     7.10
15   강서구   162        3661     5.85
16   구로구    99        4411     6.30
17   금천구    63        3977     4.90
18  영등포구   109        3717     8.60
19   동작구    82        4960     7.15
20   관악구    84        6146    10.10
21   서초구   127        3409     6.70
22   강남구   292        1870    10.15
23   송파구   169        4012    13.25
24   강동구   124        3722     5.00

In [24]:
#소아과
#url 바꿔가면서 찾기
hospital_number = {}
hospital_review_number_mean = {}
population_per_hospital = {}

for region in region_list:
    url = f"https://www.modoodoc.com/q/?search_query={region}%20소아과"
    driver = webdriver.Chrome('./chromedriver/chromedriver.exe')
    driver.implicitly_wait(2)
    driver.get(url)
    search_result = int(driver.find_element_by_class_name('color49').text[5:-1])
    hospital_number[region] = search_result
    
    req = requests.get(url)
    html = req.text
    soup = BeautifulSoup(html, "html.parser")
    review_list = soup.find_all(attrs={'class':"review-count-box ml-1"})
    striped_list = [(i.text).strip() for i in review_list]
    review_number_list = [int(j[8:-1]) for j in striped_list]
    number_mean = sum(review_number_list) / len(review_number_list)
    hospital_review_number_mean[region] = number_mean
    
    driver.quit()  # 창 닫기
    
for item in region_list:    
    population_per_hospital[item] = gu_population[item]//hospital_number[item]

    
# 일단 진료과목별로 저장해 두기
pediatric_number = hospital_number
pediatric_review = hospital_review_number_mean
pediatric_population = population_per_hospital

# 출력

pediatric_data_all = { "지역구":region_list, "소아과 수": list(hospital_number.values()) , "소아과 하나당 인구수":list(population_per_hospital.values()) ,"상위권 리뷰수":list(hospital_review_number_mean.values())}

pediatric_data = pd.DataFrame(pediatric_data_all)
pediatric_data

     지역구  소아과 수  소아과 하나당 인구수   상위권 리뷰수
0    종로구      5        32104  2.600000
1     중구     46         2957  1.550000
2    용산구     29         8460  1.200000
3    성동구     32         9526  2.250000
4    광진구     35        10397  2.850000
5   동대문구     34        10599  2.550000
6    중랑구     37        10795  3.150000
7    성북구     38        11902  1.900000
8    강북구     30        10513  1.100000
9    도봉구     28        11848  1.700000
10   노원구     47        11341  2.950000
11   은평구     36        13442  3.300000
12  서대문구     19        17064  1.157895
13   마포구     37        10404  2.400000
14   양천구     33        14001  4.500000
15   강서구     71         8354  4.850000
16   구로구     55         7940  3.000000
17   금천구     19        13187  1.421053
18  영등포구     36        11254  4.000000
19   동작구     32        12711  2.500000
20   관악구     36        14342  2.650000
21   서초구     48         9022  1.850000
22   강남구     58         9416  2.400000
23   송파구     71         9550  4.750000
24   강동구     44        10489  2.550000

In [28]:
#정형외과
#url 바꿔가면서 찾기
hospital_number = {}
hospital_review_number_mean = {}
population_per_hospital = {}

for region in region_list:
    url = f"https://www.modoodoc.com/q/?search_query={region}%20정형외과"
    driver = webdriver.Chrome('./chromedriver/chromedriver.exe')
    driver.implicitly_wait(2)
    driver.get(url)
    search_result = int(driver.find_element_by_class_name('color49').text[5:-1])
    hospital_number[region] = search_result
    
    req = requests.get(url)
    html = req.text
    soup = BeautifulSoup(html, "html.parser")
    review_list = soup.find_all(attrs={'class':"review-count-box ml-1"})
    striped_list = [(i.text).strip() for i in review_list]
    review_number_list = [int(j[8:-1]) for j in striped_list]
    number_mean = sum(review_number_list) / len(review_number_list)
    hospital_review_number_mean[region] = number_mean
    
    driver.quit()  # 창 닫기
    
for item in region_list:    
    population_per_hospital[item] = gu_population[item]//hospital_number[item]

    
# 일단 진료과목별로 저장해 두기
orthopedic_number = hospital_number
orthopedic_review = hospital_review_number_mean
orthopedic_population = population_per_hospital

# 출력

orthopedic_data_all = { "지역구":region_list, "정형외과 수": list(hospital_number.values()) , "정형외과 하나당 인구수":list(population_per_hospital.values()) ,"상위권 리뷰수":list(hospital_review_number_mean.values())}

orthopedic_data = pd.DataFrame(orthopedic_data_all)
orthopedic_data

     지역구  정형외과 수  정형외과 하나당 인구수  상위권 리뷰수
0    종로구      23          6979    10.45
1     중구     122          1115    11.60
2    용산구      21         11683     8.40
3    성동구      40          7621     9.65
4    광진구      43          8463     7.95
5   동대문구      55          6552     8.25
6    중랑구      66          6051     7.95
7    성북구      47          9623     8.05
8    강북구      45          7008     9.55
9    도봉구      41          8091     5.15
10   노원구      64          8328     9.90
11   은평구      63          7681    10.90
12  서대문구      22         14737     5.70
13   마포구      55          6999    21.75
14   양천구      59          7831    10.25
15   강서구      92          6447    13.60
16   구로구      48          9098     6.55
17   금천구      39          6424     6.10
18  영등포구      56          7234    13.65
19   동작구      38         10704    12.20
20   관악구      64          8067    20.10
21   서초구     106          4085    13.80
22   강남구     181          3017    17.35
23   송파구      98          6919    15.95
24   강동구      74          6237     9.00

In [25]:
#정신건강의학과
#url 바꿔가면서 찾기
hospital_number = {}
hospital_review_number_mean = {}
population_per_hospital = {}

for region in region_list:
    url = f"https://www.modoodoc.com/q/?search_query={region}%20정신건강의학과"
    driver = webdriver.Chrome('./chromedriver/chromedriver.exe')
    driver.implicitly_wait(2)
    driver.get(url)
    search_result = int(driver.find_element_by_class_name('color49').text[5:-1])
    hospital_number[region] = search_result
    
    req = requests.get(url)
    html = req.text
    soup = BeautifulSoup(html, "html.parser")
    review_list = soup.find_all(attrs={'class':"review-count-box ml-1"})
    striped_list = [(i.text).strip() for i in review_list]
    review_number_list = [int(j[8:-1]) for j in striped_list]
    number_mean = sum(review_number_list) / len(review_number_list)
    hospital_review_number_mean[region] = number_mean
    
    driver.quit()  # 창 닫기
    
for item in region_list:    
    population_per_hospital[item] = gu_population[item]//hospital_number[item]

    
# 일단 진료과목별로 저장해 두기
psych_number = hospital_number
psych_review = hospital_review_number_mean
psych_population = population_per_hospital

# 출력

psych_data_all = { "지역구":region_list, "정신건강의학과 수": list(hospital_number.values()) , "정신건강의학과 하나당 인구수":list(population_per_hospital.values()) ,"상위권 리뷰수":list(hospital_review_number_mean.values())}

psych_data = pd.DataFrame(psych_data_all)
psych_data

     지역구  정신건강의학과 수  정신건강의학과 하나당 인구수   상위권 리뷰수
0    종로구         33             4864  3.950000
1     중구         50             2720  2.200000
2    용산구          4            61340  5.000000
3    성동구         10            30485  3.700000
4    광진구         63             5776  2.850000
5   동대문구         24            15015  2.100000
6    중랑구         14            28529  1.500000
7    성북구         15            30152  2.133333
8    강북구         11            28672  4.181818
9    도봉구         16            20734  0.562500
10   노원구         21            25382  2.750000
11   은평구         28            17283  2.300000
12  서대문구         10            32422  2.900000
13   마포구         28            13748  5.250000
14   양천구         13            35541  1.692308
15   강서구         26            22815  3.300000
16   구로구         22            19850  4.150000
17   금천구         16            15659  1.125000
18  영등포구         18            22508  2.611111
19   동작구         16            25423  2.687500
20   관악구         23            22448  4.800000
21   서초구         51             8491  4.000000
22   강남구         98             5573  4.300000
23   송파구         44            15410  3.550000
24   강동구         32            14423  1.800000

In [30]:
all_hospital_numbers = {"지역구": region_list, "치과 수": list(dental_number.values()), "피부과 수": list(dermatic_number.values()), "안과 수": list(ophthalmic_number.values()), "성형외과 수": list(cosmetic_number.values()), "내과 수": list(internel_number.values()), "소아과 수": list(pediatric_number.values()), "정형외과 수": list(orthopedic_number.values()), "정신건강의학과 수": list(psych_number.values())}
hospital_numbers_df = pd.DataFrame(all_hospital_numbers)
hospital_numbers_df

     지역구  치과 수  피부과 수  안과 수  성형외과 수  내과 수  소아과 수  정형외과 수  정신건강의학과 수
0    종로구   195     47    23       5    44      5      23         33
1     중구   707    169   113     131   358     46     122         50
2    용산구    96     45    14       3    60     29      21          4
3    성동구   156     35    15       5    63     32      40         10
4    광진구   194     62    16       8    78     35      43         63
5   동대문구   179     31    18       9    89     34      55         24
6    중랑구   165     46    14       3    88     37      66         14
7    성북구   163     52    21       4    95     38      47         15
8    강북구   151     42    22       7   104     30      45         11
9    도봉구   129     21    15       2    61     28      41         16
10   노원구   227     67    41      17    96     47      64         21
11   은평구   209     57    23       7   107     36      63         28
12  서대문구   156     54    16       7    50     19      22         10
13   마포구   235    130    21      18   114     37      55         28
14   양천구   233     55    16       8    82     33      59         13
15   강서구   325     93    49      16   162     71      92         26
16   구로구   175     62    21       4    99     55      48         22
17   금천구   120     21    10       1    63     19      39         16
18  영등포구   278     69    88      11   109     36      56         18
19   동작구   226     57    17       5    82     32      38         16
20   관악구   251     62    25      13    84     36      64         23
21   서초구   521    253   102     237   127     48     106         51
22   강남구   804    779   177    1238   292     58     181         98
23   송파구   391    123    48      18   169     71      98         44
24   강동구   282     65    41      12   124     44      74         32